### ISSUE TITLE
Server DOWN na upgrade

### ISSUE THREAD

**Issue by bertvv** [Aaronmsv/Bachelorproefportal-TI#21]
Ik heb daarnet de upgrade willen uitvoeren voor de tool van de bachelorproef, maar die wil niet meer herstarten. Op de website zie je enkel "Server error in "/" Application", de Error log geeft dit als foutboodschap:

```
2015-02-07 22:18:37.8605|ERROR|Bachelorproef.MvcApplication|Uncatched exception!
System.InvalidOperationException: The model backing the 'BachelorproefContext' context has changed since the database was created. Consider using Code First Migrations to update the database (http://go.microsoft.com/fwlink/?LinkId=238269).
   at System.Data.Entity.CreateDatabaseIfNotExists`1.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Bachelorproef.Models.Repositories.UserRepository.FindAll()
   at Bachelorproef.MvcApplication.Application_Start()
```

Blijkbaar wil de nieuwe versie niet werken op de bestaande database?

**Comment by Aaronmsv** [comment]
Is opgelost met de nieuwe DB en verplaatsen van copromotor
