### ISSUE TITLE
Export naar pdf werkt niet

### ISSUE THREAD

**Issue by bertvv** [Aaronmsv/Bachelorproefportal-TI#30]
In de Admin-console, na klikken op de knop "Export to PDF" krijg je volgende foutboodschap.

![image](https://cloud.githubusercontent.com/assets/438140/8216026/4888cda4-1534-11e5-9b3f-cf185e433242.png)

Misschien is de oorzaak de mislukte upgrade met een inconsistente db tot gevolg.

**Comment by Aaronmsv** [comment]
Kan je de error log eens tonen?

**Comment by bertvv** [comment]
```
2015-04-20 11:23:06.6575|ERROR|Bachelorproef.MvcApplication|Uncatched exception!
System.Web.HttpException (0x80004005): The controller for path '/ExportDB' was not found or does not implement IController.
   at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)
   at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)
   at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by Aaronmsv** [comment]
Dit is zeer raar. Zeker omdat dit bij wel correct werkt en vroeger bij u ook? Het lijkt erop dat de controller niet gevonden kan worden en veel voorkomende oplossingen daarvoor zijn:

1. De controller expliciet vermelden
2. De files in dezelfde namespace/area

Beide zijn al in orde hier. Wat mij wel opvalt is dat de link niet klopt. Het path is "BPC/ExportDB" en niet "/ExportDB". De controller wordt gewoon niet meegegeven. Normaal mogen beide knoppen dan niet werken. Ik vraag me af of dit misschien browser gerelateerd is. Heb je dit ook in bv. Firefox?
